const STORAGE='japan700-tracker-v1';
const COMPLETED=new Set(['已去','想再去']);
let spots=[], state={}, onlyVisited=false;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadState(){try{state=JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{state={}}}
function saveState(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function record(id){return state[id]||{}}
function merged(s){const r=record(s.id);return {...s,status:r.status||s.status||'待確認',date:r.date||'',note:r.note||'',visited:r.visited??COMPLETED.has(r.status||s.status)}}
function isDone(s){const m=merged(s);return m.visited||COMPLETED.has(m.status)}
function setRecord(id,patch){state[id]={...record(id),...patch};saveState();render()}
function pct(a,b){return b?Math.round(a/b*100):0}
function renderSummary(){const done=spots.filter(isDone).length;const pref=new Set(spots.filter(isDone).map(x=>x.prefecture)).size;const wish=spots.filter(s=>['想去','想再去'].includes(merged(s).status)).length;$('#summary').innerHTML=`<div class="stat"><span>已完成</span><b>${done}<small> / ${spots.length}</small></b></div><div class="stat"><span>總完成率</span><b>${pct(done,spots.length)}%</b></div><div class="stat"><span>已踩都道府縣</span><b>${pref}<small> / 47</small></b></div><div class="stat"><span>願望清單</span><b>${wish}</b></div>`}
function filtered(){const q=$('#search').value.trim().toLowerCase(),r=$('#region').value,p=$('#pref').value,st=$('#status').value;return spots.filter(s=>{const m=merged(s);if(q&&!`${s.name} ${s.prefecture} ${s.region} ${s.type}`.toLowerCase().includes(q))return false;if(r&&s.region!==r)return false;if(p&&s.prefecture!==p)return false;if(st&&m.status!==st)return false;if(onlyVisited&&!isDone(s))return false;return true})}
function renderRegionProgress(){const regions=[...new Set(spots.map(s=>s.region))];$('#regionProgress').innerHTML=regions.map(r=>{const all=spots.filter(s=>s.region===r),d=all.filter(isDone).length;return `<div class="prog"><div class="prog-top"><b>${esc(r)}</b><span>${d}/${all.length} · ${pct(d,all.length)}%</span></div><div class="bar"><i style="width:${pct(d,all.length)}%"></i></div></div>`}).join('')}
function renderCards(){const list=filtered();$('#visibleCount').textContent=`目前顯示 ${list.length} 項`;$('#empty').hidden=!!list.length;$('#cards').innerHTML=list.map(s=>{const m=merged(s),done=isDone(s);return `<article class="spot ${done?'visited':''}" data-id="${esc(s.id)}"><input class="check" type="checkbox" ${done?'checked':''} aria-label="已去"><div><div class="meta"><span class="pill">${esc(s.region)}</span><span class="pill">${esc(s.prefecture)}</span><span class="pill">${esc(s.type)}</span></div><h3>${esc(s.name)}</h3><div class="sub">${esc(s.id)}</div><div class="spot-controls"><select class="status">${['待確認','想去','已去','想再去','暫不安排'].map(v=>`<option ${m.status===v?'selected':''}>${v}</option>`).join('')}</select><input class="date" type="date" value="${esc(m.date)}"><textarea class="note" placeholder="我的回憶／同行者／備註">${esc(m.note)}</textarea></div>${s.source?`<a class="source" href="${esc(s.source)}" target="_blank" rel="noopener">官方查核入口 ↗</a>`:''}</div></article>`}).join('')}
function render(){renderSummary();renderRegionProgress();renderCards();bindCards()}
function bindCards(){document.querySelectorAll('.spot').forEach(el=>{const id=el.dataset.id;el.querySelector('.check').addEventListener('change',e=>setRecord(id,{visited:e.target.checked,status:e.target.checked?(record(id).status==='想再去'?'想再去':'已去'):(record(id).status==='已去'?'待確認':record(id).status)}));el.querySelector('.status').addEventListener('change',e=>setRecord(id,{status:e.target.value,visited:COMPLETED.has(e.target.value)}));el.querySelector('.date').addEventListener('change',e=>{state[id]={...record(id),date:e.target.value};saveState()});el.querySelector('.note').addEventListener('change',e=>{state[id]={...record(id),note:e.target.value};saveState()})})}
function initFilters(){const regions=[...new Set(spots.map(s=>s.region))];const prefs=[...new Set(spots.map(s=>s.prefecture))];$('#region').insertAdjacentHTML('beforeend',regions.map(v=>`<option>${esc(v)}</option>`).join(''));$('#pref').insertAdjacentHTML('beforeend',prefs.map(v=>`<option>${esc(v)}</option>`).join(''));['search','region','pref','status'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));$('#onlyVisited').addEventListener('click',()=>{onlyVisited=!onlyVisited;$('#onlyVisited').textContent=onlyVisited?'顯示全部':'只看已踩';render()})}
function exportBackup(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`japan700-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
$('#exportBtn').addEventListener('click',exportBackup);$('#importFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());state=obj.state||obj;saveState();render();alert('備份已匯入。')}catch{alert('這個備份檔無法讀取。')}e.target.value=''})
$('#resetBtn').addEventListener('click',()=>{if(confirm('確定清除這台裝置上的所有勾選、日期與備註？')){state={};saveState();render()}})
Promise.all([1,2,3,4].map(i=>fetch(`data.${i}.txt`).then(r=>{if(!r.ok)throw new Error('data');return r.text()}))).then(async parts=>{const bin=Uint8Array.from(atob(parts.join('')),c=>c.charCodeAt(0));const stream=new Blob([bin]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text())}).then(d=>{spots=d;loadState();initFilters();render()}).catch(()=>{$('#empty').hidden=false;$('#empty').textContent='資料載入失敗，請重新整理頁面。'});
